name: "Build FlowBlot projects"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Python requirements
      run: pip install -r ./requirements.txt

    - name: Install .NET 4.x build tool
      run: |
        sudo apt-get update
        sudo apt-get install mono-xbuild

    - name: Build each project separately
      run: |
        ./check_build.py
